# H2 In-Memory DB Config
spring.datasource.url=jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate DDL auto
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Server port
server.port=8080
